[package]
name = "lusque"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.9.2"
jni = "0.21.1"
lazy_static = "1.4.0"
once_cell = "1.18.0"
