/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MainKt */

#ifndef _Included_MainKt
#define _Included_MainKt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MainKt
 * Method:    compile
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_MainKt_compile
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
